# -*- coding: utf-8 -*-
"""SINGLE_LINE_CALCULATOR_PROJECT_BY_KORUKONDA_YESU_KISHORE.ipynb.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfxhgSRy89babOmStv94Nt-gVUVudEa0

# PROJECT - **UNIVERSAL SIMPLE SINGLE LINE CALCULATOR**
## PROGRAMMER NAME - KORUKONDA YESU KISHORE

PLEASE WRITE YOUR EXPRESSIONS IN SINGLE LINE (FOR EXAMPLE: 20 + 10)
"""

print(eval(input("EXPRESSION :: ")))